"""IaC generator for IAI.

Reads the platform manifest (via ManifestReader), enforces the greenfield
criticality contract, resolves effective (transitive) criticality, and renders
OpenTofu HCL for AWS and GCP resources. Each resource name maps to a dedicated
renderer; criticality is injected into AWS `tags` and GCP `labels` blocks.

Library scope: stdlib + ruamel.yaml only (ManifestReader pulls in ruamel.yaml).
This module is a library: no CLI entry point.

v2: Multi-cloud (AWS + GCP). AWS: EC2 instance + security group (default VPC).
GCP: GCS bucket with uniform bucket-level access.
"""

import os

from agent.manifest_reader import ManifestReader

_HEADER = (
    "# Generated by IaCGenerator from manifest.yaml — do not edit by hand.\n"
    "# Re-run the generator to update. Engine: OpenTofu (drop-in HCL compatible).\n"
)


def _tf_name(s: str) -> str:
    return s.replace("-", "_")


class IaCGenerator:
    def __init__(self, manifest_path: str, env: str = "staging") -> None:
        self._reader = ManifestReader(manifest_path)
        self._env = env
        self._RENDERERS = {
            "app-tier": self._render_app_tier,
            "export-bucket": self._render_export_bucket,
        }

    def validate_greenfield(self) -> None:
        resources = self._reader.get_resources(self._env)
        missing = [n for n, r in resources.items() if "criticality" not in r]
        if missing:
            raise ValueError(
                "greenfield contract violated: the following resources lack a "
                "'criticality' field: " + ", ".join(missing)
            )

    def generate_to_string(self) -> str:
        self.validate_greenfield()
        criticality = self._reader.resolve_criticality(self._env)
        resources = self._reader.get_resources(self._env)

        blocks = [_HEADER.rstrip("\n")]
        for name, resource in resources.items():
            renderer = self._RENDERERS.get(name)
            if renderer is None:
                continue
            blocks.append(renderer(name, resource, criticality[name]))

        return "\n\n".join(blocks) + "\n"

    def generate(self, output_path: str) -> None:
        parent = os.path.dirname(output_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(self.generate_to_string())

    # --- Tag / label helpers ------------------------------------------------

    def _aws_tags(self, criticality: str) -> str:
        return (
            "  tags = {\n"
            "    environment = var.environment\n"
            '    owner       = "payments-team"\n'
            f'    criticality = "{criticality}"\n'
            "  }"
        )

    def _gcp_labels(self, criticality: str) -> str:
        return (
            "  labels = {\n"
            "    environment = var.environment\n"
            '    owner       = "payments-team"\n'
            f'    criticality = "{criticality}"\n'
            "  }"
        )

    # --- Renderers ----------------------------------------------------------

    def _render_app_tier(self, name: str, resource: dict, criticality: str) -> str:
        tf = _tf_name(name)
        sg = (
            "# Intentionally over-permissive: known-bad form for the security gate to flag.\n"
            "# Port 22 open to 0.0.0.0/0 is the CKV_AWS_24 finding the gate must catch.\n"
            f'resource "aws_security_group" "{tf}" {{\n'
            '  name        = "payments-app-tier"\n'
            '  description = "App tier security group for payments staging"\n'
            "\n"
            "  ingress {\n"
            '    description = "SSH - intentionally open to internet for security gate demo"\n'
            "    from_port   = 22\n"
            "    to_port     = 22\n"
            '    protocol    = "tcp"\n'
            '    cidr_blocks = ["0.0.0.0/0"]\n'
            "  }\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        instance = (
            "\n# App tier: EC2 instance in the default VPC.\n"
            "# AMI and instance type supplied via variables. IMDSv2 enforced (CKV_AWS_79 passes).\n"
            "# root_block_device is declared explicitly so Infracost produces a deterministic estimate.\n"
            f'resource "aws_instance" "{tf}" {{\n'
            "  ami                    = var.app_tier_ami\n"
            '  instance_type          = "t3.micro"\n'
            f"  vpc_security_group_ids = [aws_security_group.{tf}.id]\n"
            "\n"
            "  metadata_options {\n"
            '    http_endpoint               = "enabled"\n'
            '    http_tokens                 = "required"\n'
            "    http_put_response_hop_limit = 1\n"
            "  }\n"
            "\n"
            "  root_block_device {\n"
            '    volume_type = "gp3"\n'
            "    volume_size = 8\n"
            "  }\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        return sg + "\n" + instance

    def _render_export_bucket(self, name: str, resource: dict, criticality: str) -> str:
        # Name is declared explicitly in the manifest so it's visible and auditable there.
        # Fall back to the iai-export-{environment} convention if not set.
        bucket_name = resource.get("name") or f"iai-export-${{var.environment}}"
        return (
            "# GCS export bucket. Uniform bucket-level access is enforced (CKV_GCP_29 passes).\n"
            '# Bucket name sourced from manifest.yaml (export-bucket.name).\n'
            'resource "google_storage_bucket" "export_bucket" {\n'
            f'  name          = "{bucket_name}"\n'
            '  location      = "ASIA-SOUTHEAST1"\n'
            "  force_destroy = true\n"
            "\n"
            "  uniform_bucket_level_access = true\n"
            "\n"
            f"{self._gcp_labels(criticality)}\n"
            "}"
        )
