"""IaC generator for IAI.

Reads the platform manifest (via ManifestReader), enforces the greenfield
criticality contract, resolves effective (transitive) criticality, and renders
OpenTofu HCL for AWS resources. Each resource name maps to a dedicated renderer;
criticality is injected into AWS `tags` blocks.

Library scope: stdlib + ruamel.yaml only (ManifestReader pulls in ruamel.yaml).
This module is a library: no CLI entry point.

v1: AWS-only. Multi-cloud support deferred to v2.
"""

import os

from agent.manifest_reader import ManifestReader

_HEADER = (
    "# Generated by IaCGenerator from manifest.yaml — do not edit by hand.\n"
    "# Re-run the generator to update. Engine: OpenTofu (drop-in HCL compatible).\n"
)


def _tf_name(s: str) -> str:
    return s.replace("-", "_")


class IaCGenerator:
    def __init__(self, manifest_path: str, env: str = "staging") -> None:
        self._reader = ManifestReader(manifest_path)
        self._env = env
        self._RENDERERS = {
            "payments-vpc": self._render_payments_vpc,
            "payments-db": self._render_payments_db,
            "app-tier": self._render_app_tier,
        }

    def validate_greenfield(self) -> None:
        resources = self._reader.get_resources(self._env)
        missing = [n for n, r in resources.items() if "criticality" not in r]
        if missing:
            raise ValueError(
                "greenfield contract violated: the following resources lack a "
                "'criticality' field: " + ", ".join(missing)
            )

    def generate_to_string(self) -> str:
        self.validate_greenfield()
        criticality = self._reader.resolve_criticality(self._env)
        resources = self._reader.get_resources(self._env)

        blocks = [_HEADER.rstrip("\n")]
        for name, resource in resources.items():
            renderer = self._RENDERERS.get(name)
            if renderer is None:
                continue
            blocks.append(renderer(name, resource, criticality[name]))

        return "\n\n".join(blocks) + "\n"

    def generate(self, output_path: str) -> None:
        parent = os.path.dirname(output_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(self.generate_to_string())

    # --- Tag / label helpers ------------------------------------------------

    def _aws_tags(self, criticality: str) -> str:
        return (
            "  tags = {\n"
            "    environment = var.environment\n"
            '    owner       = "payments-team"\n'
            f'    criticality = "{criticality}"\n'
            "  }"
        )

    # --- Renderers ----------------------------------------------------------

    def _render_payments_vpc(self, name: str, resource: dict, criticality: str) -> str:
        tf = _tf_name(name)
        vpc = (
            f'resource "aws_vpc" "{tf}" {{\n'
            '  cidr_block = "10.0.0.0/16"\n'
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        subnet_az1 = (
            'resource "aws_subnet" "payments_private_az1" {\n'
            f"  vpc_id                  = aws_vpc.{tf}.id\n"
            '  cidr_block              = "10.0.1.0/24"\n'
            '  availability_zone       = "ap-southeast-5a"\n'
            "  map_public_ip_on_launch = false\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        subnet_az2 = (
            'resource "aws_subnet" "payments_private_az2" {\n'
            f"  vpc_id                  = aws_vpc.{tf}.id\n"
            '  cidr_block              = "10.0.2.0/24"\n'
            '  availability_zone       = "ap-southeast-5b"\n'
            "  map_public_ip_on_launch = false\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        subnet_group = (
            'resource "aws_db_subnet_group" "payments" {\n'
            '  name       = "payments-staging"\n'
            "  subnet_ids = [aws_subnet.payments_private_az1.id, aws_subnet.payments_private_az2.id]\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        return "\n\n".join([vpc, subnet_az1, subnet_az2, subnet_group])

    def _render_payments_db(self, name: str, resource: dict, criticality: str) -> str:
        tf = _tf_name(name)
        return (
            f'resource "aws_db_instance" "{tf}" {{\n'
            '  identifier           = "payments-staging"\n'
            '  engine               = "postgres"\n'
            '  engine_version       = "16"\n'
            '  instance_class       = "db.t3.small"\n'
            "  allocated_storage    = 20\n"
            '  storage_type         = "gp3"\n'
            "  storage_encrypted    = true\n"
            "  publicly_accessible  = false\n"
            "  skip_final_snapshot  = true\n"
            "  db_subnet_group_name = aws_db_subnet_group.payments.name\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )

    def _render_app_tier(self, name: str, resource: dict, criticality: str) -> str:
        tf = _tf_name(name)
        sg = (
            "# Intentionally over-permissive: known-bad form for the security gate to flag.\n"
            "# Port 22 open to 0.0.0.0/0 is the CKV_AWS_24 finding the gate must catch.\n"
            f'resource "aws_security_group" "{tf}" {{\n'
            '  name        = "payments-app-tier"\n'
            '  description = "App tier security group for payments staging"\n'
            "  vpc_id      = aws_vpc.payments_vpc.id\n"
            "\n"
            "  ingress {\n"
            '    description = "SSH - intentionally open to internet for security gate demo"\n'
            "    from_port   = 22\n"
            "    to_port     = 22\n"
            '    protocol    = "tcp"\n'
            '    cidr_blocks = ["0.0.0.0/0"]\n'
            "  }\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        instance = (
            "\n# App tier: runs pre-baked image provisioned by CI/Packer upstream (out of scope).\n"
            "# The AMI variable must be supplied at runtime.\n"
            f'resource "aws_instance" "{tf}_instance" {{\n'
            "  ami                    = var.app_tier_ami\n"
            '  instance_type          = "t3.micro"\n'
            "  subnet_id              = aws_subnet.payments_private_az1.id\n"
            f"  vpc_security_group_ids = [aws_security_group.{tf}.id]\n"
            "\n"
            f"{self._aws_tags(criticality)}\n"
            "}"
        )
        return sg + "\n" + instance

